name: event filters
on: 
  push:
    branches:
      - 'ma*'
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: first_step
        run : echo "change is there in the main branch"
    
