name: event filters
on: 
  push:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: first_step
        run : echo "change is there in the main branch"
    
