name: first_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
      - run:  echo "printed greeting"
      - name: ok by 
      - run:  echo "printed bye"
