name: sequential 
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: echo "first step"
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: second job
        run: echo "second job"
        
    
