name: upload artifacts
on: push 
jobs:      
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        uses: actions/upload-artifact@v4
        with: 
          name: uploaded_file
          path: /test_commit.py
        
          
    
  
